server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;SelectMethod=cursor;databasename=xsk_demo_local;username=sa;password=sasa
#      jdbc:mysql://127.0.0.1:3306/spring-boot-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
